project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3: KDE"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03-KDE.html"
          - text: "In-class Exercise 3: NKDE"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03-NKDE.html"
          - text: "In-class Exercise 4: Spatial Weights"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5: Spatial Autocorrelation"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 7: Notes on `sfdep` methods"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 8: HPM"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2: Geospatial Data Wrangling"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02_Part1.html"
          - text: "Take-home Exercise 2: Report and Analysis"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02_Part2.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    toc-location: left

editor: source

